name: PointGrabber
main: com.projectreddog.pointgrabber.PointGrabber
version: .01
commands:
   pointpvp:
      description: Grab the coordinates where you are standing. [yaw] will include yaw in point data.
      usage: /<command> [yaw]
   pointcapture:
      description: Grab the coordinates where you are standing. [pointnumber] overrides the current numbering.
      usage: /<command> radius displayname time [pointnumber]
   pointnewsection:
      description: Add spacing and indicator of new section in file.
      usage: /<command> [comment]
   pointother:
      description: Grab the coordinates where you are standing. Different heading names: LobbySpawn, Spawn (includes yaw), Penalty.
      usage: /<command> name
   pointsetnumber:
      description: Change the current numbering value.
      usage: /<command> (pvp or capture) pointnumber